apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: pod-reader
rules: 
- apiGroups: [""] #indicates the core api group
  verbs: ["get", "watch", "list"]
  resources: ["pods", "pods/logs"] 
